using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace KapaliDevreOdemeSistemi
{
    public partial class BaseForm : Form
    {
        public BaseForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
             
        }

        public void ButonIlkDurum()
        {
            btnNewRecord.Enabled = true;
            btnSave.Enabled = false;
            btnUpdate.Enabled = false;
            btnDelete.Enabled = false;
            btnFormClear.Enabled = false;
            btnReturn.Enabled = false;
            gbData.Enabled = false;

        }
        public void ButonYeniKayitDurum()
        {
            btnNewRecord.Enabled = false;
            btnSave.Enabled = true;
            btnUpdate.Enabled = false;
            btnDelete.Enabled = false;
            btnFormClear.Enabled = true;
            btnReturn.Enabled = true;
            gbData.Enabled = true;
        }
        public void ButonAramaDurum()
        {
            btnNewRecord.Enabled = false;
            btnSave.Enabled = false;
            btnUpdate.Enabled = true;
            btnDelete.Enabled = true;
            btnFormClear.Enabled = true;
            btnReturn.Enabled = true;
            gbData.Enabled = true;
        }

        protected virtual void btnNewRecord_Click(object sender, EventArgs e)
        {

        }
        protected virtual void btnSave_Click(object sender, EventArgs e)
        {

        }
        protected virtual void btnUpdate_Click(object sender, EventArgs e)
        {

        }
        protected virtual void btnDelete_Click(object sender, EventArgs e)
        {

        }
        protected virtual void btnFormClear_Click(object sender, EventArgs e)
        {

        }
        protected virtual void btnReturn_Click(object sender, EventArgs e)
        {

        }
        protected virtual void gvMemberList_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
        }
    }
}
